[package]
name = "hydrogen_crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.12", features = ["gzip", "brotli", "deflate"] }
tokio = { version = "1", features = ["full"] }
