
FROM rust:latest AS builder

WORKDIR /app

COPY . .

RUN cargo build --release

FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/target/release/stalker /usr/local/bin/stalker

CMD ["stalker"]
