[package]
name = "hydrogen_ingestion"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
hydrogen_common = { path = "../hydrogen_common" }
chrono = "0.4.19"