name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Set up Rust
      uses: actions/checkout@v4
      with:
          toolchain: nightly-2024
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run
      run: cargo run
